### ISSUE TITLE
Настройка NavigationGraph

### ISSUE THREAD

**Issue by ValentinPside** [Demonided/practicum-android-diploma#4]
- [ ] Сделать одну активити которая будет хранить в себе 3 фрагмента навигации
- [ ] Добавить menu для 3х фрагментов: 
          - Поиск
          - Избранное
          - Разработчики

**Comment by Demonided** [comment]
Добавьте меню для фрагментов что бы можно было при запуске приложение навигироваться по ним.
Так же добавьте к фрагментам tools и указать фрагмент xml к которому он относится что бы схематично было его видно в графе
